using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Web3270.Tn3270.Screen;

namespace Web3270.Tn3270.DataStream;

/// <summary>
/// Parses an inbound 3270 data stream record (everything between the
/// command byte and the EOR marker) and applies its effects to a
/// <see cref="ScreenBuffer"/>.
///
/// Inside a write, the parser tracks a "running" extended attribute
/// triplet (foreground, background, highlight). SF/SFE re-seed the
/// running state from the new field; SA modifies it pair-wise; every
/// character write copies the running state onto its target cell.
/// That is what lets a single field carry per-character colour changes
/// (e.g. the multicoloured TK5 banner that hosts paint via SA orders).
/// </summary>
public sealed class Tn3270DataStreamParser
{
    private readonly ScreenBuffer _buffer;
    private readonly ILogger _log;

    public Tn3270DataStreamParser(ScreenBuffer buffer, ILogger logger = null)
    {
        ArgumentNullException.ThrowIfNull(buffer);
        _buffer = buffer;
        _log = logger ?? NullLogger.Instance;
    }

    public WriteControlCharacter? LastWcc { get; private set; }

    /// <summary>
    /// Reply payload generated by the parser when the host issues a
    /// Read-style command (WSF Read Partition Query, RB, RM, RMA). The
    /// session reads this after every <c>Process</c> call and forwards
    /// the bytes back to the host on its own.
    /// </summary>
    public byte[] PendingReply { get; private set; }

    public Tn3270CommandKind Process(ReadOnlySpan<byte> record)
    {
        PendingReply = null;
        if (record.IsEmpty) 
            return Tn3270CommandKind.Unknown;

        var cmd = record[0];
        var rest = record[1..];
        var kind = Classify(cmd);

        switch (kind)
        {
            case Tn3270CommandKind.EraseWrite:
            case Tn3270CommandKind.EraseWriteAlt:
                _buffer.EraseAll();
                ApplyWrite(rest);
                break;
            case Tn3270CommandKind.Write:
                ApplyWrite(rest);
                break;
            case Tn3270CommandKind.EraseAllUnprotected:
                _buffer.EraseAllUnprotected();
                _buffer.KeyboardLocked = false;
                break;
            case Tn3270CommandKind.WriteStructured:
                ApplyWriteStructuredField(rest);
                break;
            case Tn3270CommandKind.ReadBuffer:
            case Tn3270CommandKind.ReadModified:
            case Tn3270CommandKind.ReadModifiedAll:
                break;
            default:
                _log.UnknownCommand(cmd);
                break;
        }

        return kind;
    }

    /// <summary>
    /// Process a Write Structured Field (WSF) record. The interesting
    /// case for terminal logon is Read Partition Query — the parser
    /// stages a Query Reply payload that the session sends back to the
    /// host immediately, so VTAM can run BIND with full knowledge of
    /// our capabilities.
    /// </summary>
    private void ApplyWriteStructuredField(ReadOnlySpan<byte> data)
    {
        _log.WsfReceived(data.Length);
        var p = 0;
        while (p < data.Length)
        {
            if (p + 2 > data.Length) 
                return;
            var sfLen = (data[p] << 8) | data[p + 1];
            if (sfLen == 0) sfLen = data.Length - p;
            if (sfLen < 3 || p + sfLen > data.Length) 
                return;

            var sfType = data[p + 2];
            switch (sfType)
            {
                case StructuredFieldType.ReadPartition:
                    HandleReadPartition(data.Slice(p + 3, sfLen - 3));
                    break;
                case StructuredFieldType.EraseReset:
                    HandleEraseReset(data.Slice(p + 3, sfLen - 3));
                    break;
                case StructuredFieldType.SetReplyMode:
                    // Acknowledged but no-op — we always emit field-level replies.
                    break;
                case StructuredFieldType.Outbound3270DS:
                    // Embedded write — process recursively starting from the
                    // partition-id+command after the SF header.
                    if (sfLen >= 5)
                    {
                        var inner = data.Slice(p + 4, sfLen - 4); // skip partition id
                        Process(inner);
                    }

                    break;
                default:
                    _log.UnknownStructuredField(sfType);
                    break;
            }

            p += sfLen;
        }
    }

    private void HandleReadPartition(ReadOnlySpan<byte> data)
    {
        // data[0] = partition id (we treat 0xFF = "any")
        // data[1] = operation: 0x02 = QueryAll, 0x03 = QueryList
        if (data.Length < 2) 
            return;
        var op = data[1];
        if (op == 0x02 || op == 0x03)
        {
            _log.QueryReplyDispatched();
            PendingReply = new QueryReplyBuilder(_buffer.Rows, _buffer.Columns).Build();
        }
    }

    private void HandleEraseReset(ReadOnlySpan<byte> data)
    {
        // data[0] = flag byte. Bit 0x80 set => alternate screen.
        // Either way the buffer is wiped to the chosen size.
        _buffer.EraseAll();
        _buffer.KeyboardLocked = false;
    }

    private static Tn3270CommandKind Classify(byte cmd)
    {
        return cmd switch
        {
            Tn3270Command.Write or 0x01 => Tn3270CommandKind.Write,
            Tn3270Command.EraseWrite or 0x05 => Tn3270CommandKind.EraseWrite,
            Tn3270Command.EraseWriteAlt or 0x0D => Tn3270CommandKind.EraseWriteAlt,
            Tn3270Command.ReadBuffer or 0x02 => Tn3270CommandKind.ReadBuffer,
            Tn3270Command.ReadModified or 0x06 => Tn3270CommandKind.ReadModified,
            Tn3270Command.ReadModifiedAll or 0x0E => Tn3270CommandKind.ReadModifiedAll,
            Tn3270Command.EraseAllUnprot or 0x0F => Tn3270CommandKind.EraseAllUnprotected,
            Tn3270Command.WriteStructured or 0x11 => Tn3270CommandKind.WriteStructured,
            _ => Tn3270CommandKind.Unknown
        };
    }

    private void ApplyWrite(ReadOnlySpan<byte> data)
    {
        if (data.IsEmpty) 
            return;

        var wcc = new WriteControlCharacter(data[0]);
        LastWcc = wcc;
        
        if (wcc.SoundAlarm) 
            _buffer.AlarmTriggered = true;
        if (wcc.KeyboardRestore) 
            _buffer.KeyboardLocked = false;
        if (wcc.ResetMdt)
            ResetAllMdt();

        var pos = _buffer.CursorAddress;
        byte runFg = 0, runBg = 0, runHi = 0;

        var i = 1;
        while (i < data.Length)
        {
            var b = data[i];
            switch (b)
            {
                case Tn3270Order.SF:
                    if (i + 1 >= data.Length) 
                        return;
                    pos = ApplyStartField(pos, data[i + 1]);
                    runFg = runBg = runHi = 0;
                    i += 2;
                    break;

                case Tn3270Order.SFE:
                    i = ApplySfe(data, i, ref pos, out runFg, out runBg, out runHi);
                    break;

                case Tn3270Order.SBA:
                    if (i + 2 >= data.Length) 
                        return;
                    pos = _buffer.Wrap(BufferAddress.Decode(data[i + 1], data[i + 2]));
                    i += 3;
                    break;

                case Tn3270Order.IC:
                    _buffer.CursorAddress = pos;
                    i += 1;
                    break;

                case Tn3270Order.PT:
                    pos = ProgramTab(pos);
                    i += 1;
                    break;

                case Tn3270Order.RA:
                    i = ApplyRepeatToAddress(data, i, ref pos, runFg, runBg, runHi);
                    break;

                case Tn3270Order.EUA:
                    i = ApplyEraseUnprotectedToAddress(data, i, ref pos);
                    break;

                case Tn3270Order.SA:
                    i = ApplySetAttribute(data, i, ref runFg, ref runBg, ref runHi);
                    break;

                case Tn3270Order.MF:
                    i = ApplyModifyField(data, i, ref pos);
                    break;

                case Tn3270Order.GE:
                    if (i + 1 >= data.Length)
                        return;
                    WriteCharacter(ref pos, data[i + 1], runFg, runBg, runHi);
                    i += 2;
                    break;

                case FormatControlOrder.Null:
                case FormatControlOrder.FormFeed:
                case FormatControlOrder.CarriageReturn:
                case FormatControlOrder.NewLine:
                case FormatControlOrder.EndOfMedium:
                case FormatControlOrder.Duplicate:
                case FormatControlOrder.FieldMark:
                case FormatControlOrder.Substitute:
                case FormatControlOrder.EightOnes:
                    // dm3270-style: every format-control byte renders as a
                    // single EBCDIC space. The data-stream itself uses these
                    // as "blank" placeholders.
                    WriteCharacter(ref pos, 0x40, runFg, runBg, runHi);
                    i += 1;
                    break;

                default:
                    WriteCharacter(ref pos, b, runFg, runBg, runHi);
                    i += 1;
                    break;
            }
        }
    }

    private int ApplyStartField(int pos, byte attrByte)
    {
        var attr = new FieldAttr(attrByte);
        var cell = _buffer[pos];
        cell.Reset();
        cell.IsFieldAttribute = true;
        cell.Attribute = attr;
        cell.Character = 0x40;
        return _buffer.Wrap(pos + 1);
    }

    private int ApplySfe(ReadOnlySpan<byte> data, int idx, ref int pos,
        out byte fieldFg, out byte fieldBg, out byte fieldHi)
    {
        fieldFg = fieldBg = fieldHi = 0;
        if (idx + 1 >= data.Length) 
            return data.Length;

        var pairCount = data[idx + 1];
        var attrByte = (byte)0xC0;
        var p = idx + 2;
        for (var k = 0; k < pairCount; k++)
        {
            if (p + 1 >= data.Length)
                break;
            var type = data[p];
            var value = data[p + 1];
            switch (type)
            {
                case ExtendedAttributeType.FieldAttribute: attrByte = value; break;
                case ExtendedAttributeType.ForegroundColor: fieldFg = value; break;
                case ExtendedAttributeType.BackgroundColor: fieldBg = value; break;
                case ExtendedAttributeType.Highlighting: fieldHi = value; break;
            }

            p += 2;
        }

        var cell = _buffer[pos];
        cell.Reset();
        cell.IsFieldAttribute = true;
        cell.Attribute = new FieldAttr(attrByte);
        cell.Foreground = fieldFg;
        cell.Background = fieldBg;
        cell.Highlight = fieldHi;
        cell.Character = 0x40;

        pos = _buffer.Wrap(pos + 1);
        return p;
    }

    private int ApplyRepeatToAddress(ReadOnlySpan<byte> data, int idx, ref int pos,
        byte fg, byte bg, byte hi)
    {
        if (idx + 3 >= data.Length)
            return data.Length;
        var target = _buffer.Wrap(BufferAddress.Decode(data[idx + 1], data[idx + 2]));
        var fillByte = data[idx + 3];

        var consumed = idx + 4;
        if (fillByte == Tn3270Order.GE)
        {
            if (consumed >= data.Length) 
                return data.Length;
            fillByte = data[consumed];
            consumed += 1;
        }

        // 3270 architecture: when current pen position equals the RA target,
        // the RA fills the ENTIRE buffer with the fill character. Without
        // this dm3270-style behaviour the parser silently drops a full-screen
        // fill and the host's expected blank canvas never appears.
        if (pos == target)
        {
            for (var n = 0; n < _buffer.Size; n++)
                WriteCharacter(ref pos, fillByte, fg, bg, hi);
            return consumed;
        }

        var safety = _buffer.Size;
        while (pos != target && safety-- > 0) 
            WriteCharacter(ref pos, fillByte, fg, bg, hi);
        return consumed;
    }

    private int ApplyEraseUnprotectedToAddress(ReadOnlySpan<byte> data, int idx, ref int pos)
    {
        if (idx + 2 >= data.Length) 
            return data.Length;
        var target = _buffer.Wrap(BufferAddress.Decode(data[idx + 1], data[idx + 2]));
        var safety = _buffer.Size;
        while (pos != target && safety-- > 0)
        {
            var cell = _buffer[pos];
            if (!cell.IsFieldAttribute)
            {
                var field = _buffer.FieldAt(pos);
                if (field is null || !field.Protected) cell.Character = 0x00;
            }

            pos = _buffer.Wrap(pos + 1);
        }

        return idx + 3;
    }

    private static int ApplySetAttribute(ReadOnlySpan<byte> data, int idx,
        ref byte runFg, ref byte runBg, ref byte runHi)
    {
        if (idx + 2 >= data.Length) 
            return data.Length;
        var type = data[idx + 1];
        var value = data[idx + 2];
        switch (type)
        {
            case ExtendedAttributeType.ResetAll:
                runFg = runBg = runHi = 0;
                break;
            case ExtendedAttributeType.ForegroundColor: runFg = value; break;
            case ExtendedAttributeType.BackgroundColor: runBg = value; break;
            case ExtendedAttributeType.Highlighting: runHi = value; break;
        }

        return idx + 3;
    }

    private int ApplyModifyField(ReadOnlySpan<byte> data, int idx, ref int pos)
    {
        if (idx + 1 >= data.Length)
            return data.Length;
        var pairs = data[idx + 1];
        var p = idx + 2;
        var addr = _buffer.Wrap(pos - 1);
        var cell = _buffer[addr];
        if (!cell.IsFieldAttribute) 
            return p + pairs * 2;

        for (var k = 0; k < pairs; k++)
        {
            if (p + 1 >= data.Length)
                break;
            var type = data[p];
            var value = data[p + 1];
            switch (type)
            {
                case ExtendedAttributeType.FieldAttribute: cell.Attribute = new FieldAttr(value); break;
                case ExtendedAttributeType.ForegroundColor: cell.Foreground = value; break;
                case ExtendedAttributeType.BackgroundColor: cell.Background = value; break;
                case ExtendedAttributeType.Highlighting: cell.Highlight = value; break;
            }

            p += 2;
        }

        return p;
    }

    private int ProgramTab(int pos)
    {
        var n = _buffer.Size;
        for (var s = 1; s <= n; s++)
        {
            var p = _buffer.Wrap(pos + s);
            var c = _buffer[p];
            if (c.IsFieldAttribute && !c.Attribute.Protected)
                return _buffer.Wrap(p + 1);
        }

        return pos;
    }

    private void WriteCharacter(ref int pos, byte ebcdic, byte fg, byte bg, byte hi)
    {
        var cell = _buffer[pos];
        cell.IsFieldAttribute = false;
        cell.Character = ebcdic;
        cell.Foreground = fg;
        cell.Background = bg;
        cell.Highlight = hi;
        // The host owns this cell now — clear any prior user-modified mark
        // so the next read-modified does not echo it as if the user typed it.
        cell.Modified = false;
        pos = _buffer.Wrap(pos + 1);
    }

    private void ResetAllMdt()
    {
        foreach (var cell in _buffer.EnumerateAll())
        {
            if (cell.IsFieldAttribute) 
                cell.Attribute = cell.Attribute.WithModified(false);
            cell.Modified = false;
        }
    }
}

public enum Tn3270CommandKind
{
    Unknown,
    Write,
    EraseWrite,
    EraseWriteAlt,
    EraseAllUnprotected,
    ReadBuffer,
    ReadModified,
    ReadModifiedAll,
    WriteStructured
}